Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MOCP.Models;
using MOCP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MOCP.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourse _Course;
        private readonly IMentor _Mentor;
        private readonly IDepartment _Department;
        public CourseController(ICourse _ICourse, IMentor _IMentor, IDepartment _IDepartment)
        {
            _Course = _ICourse;
            _Department = _IDepartment;
            _Mentor = _IMentor;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_Course.GetCourses);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Departments = _Department.GetDepartments;
            ViewBag.Mentors = _Mentor.GetMentors;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Course model)
        {
            if (ModelState.IsValid)
            {
                _Course.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                Course model = _Course.GetCourse(Id);
                return View(model);
            }
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Course.Remove(Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Course.GetCourse(Id));
        }
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MOCP.Models;
using MOCP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace MOCP.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee _Employee;
        private readonly IDepartment _Department;
        private readonly IPosition _Position;
        private readonly ICourse _Course;

        public EmployeeController(IEmployee _IEmployee, IDepartment _IDepartment, IPosition _IPosition, ICourse _ICourse)
        {
            _Employee = _IEmployee;
            _Department = _IDepartment;
            _Position = _IPosition;
            _Course = _ICourse;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View(_Employee.GetEmployees);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Departments = _Department.GetDepartments;
            ViewBag.Positions = _Position.GetPositions;
            ViewBag.Courses = _Course.GetCourses;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee model)
        {
            if (ModelState.IsValid)
            {
                _Employee.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                Employee model = _Employee.GetEmployee(Id);
                return View(model);
            }
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Employee.Remove(Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Employee.GetEmployee(Id));
        }
    }
}

Controllers/MentorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MOCP.Models;
using MOCP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MOCP.Controllers
{
    public class MentorController : Controller
    {
        private readonly IMentor _Mentor;
        private readonly IDepartment _Department;
        public MentorController(IMentor _IMentor, IDepartment _IDepartment)
        {
            _Mentor = _IMentor;
            _Department = _IDepartment;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_Mentor.GetMentors);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Departments = _Department.GetDepartments;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Mentor model)
        {
            if (ModelState.IsValid)
            {
                _Mentor.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                Mentor model = _Mentor.GetMentor(Id);
                return View(model);
            }
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Mentor.Remove(Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Mentor.GetMentor(Id));
        }
    }
}

Controllers/PositionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MOCP.Models;
using MOCP.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MOCP.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPosition _Position;
        public PositionController(IPosition _IPosition)
        {
            _Position = _IPosition;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_Position.GetPositions);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Position model)
        {
            if(ModelState.IsValid)
            {
                _Position.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                Position model = _Position.GetPosition(Id);
                return View(model);
            }
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _Position.Remove(Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Position.GetPosition(Id));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MOCP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MOCP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Position" asp-action="Index">Position</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mentor" asp-action="Index">Mentors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MOCP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>